model_dir: my_model_directory/run/

data:
  train_features_file: my_model_directory/train.fr.bpe
  train_labels_file: my_model_directory/train.en.bpe
  eval_features_file: my_model_directory/ep7_dev.fr.bpe
  eval_labels_file: my_model_directory/ep7_dev.en.bpe
  source_words_vocabulary: my_model_directory/vocab.fr
  target_words_vocabulary: my_model_directory/vocab.en

train:
  batch_size: 1024
  save_checkpoints_steps: 1000
  maximum_features_length: 50
  maximum_labels_length: 50

  eval:
    eval_delay: 3600  # Every 1 hour
    external_evaluators: BLEU
infer:
    batch_size: 16